services:
  llm_ds:
    container_name: streamlit
    build: .
    ports:
      - "9090:8501"
    volumes:
      - ./tsundoku-ai/src:/app
      - ./book:/app/book
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY